config/routes.rb
Rails.application.routes.draw do
  root 'messages#index'
  resources :messages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  # idからメッセージを取り出す操作は他でも必要となるので最初からまとめておきます
  before_action :set_message, only: %i[destroy edit update]

  def index
    @messages = Message.all
  end

  # 新規投稿用のフォームに置き換えることだけに使用する
  def new
  end

  def create
    @message = Message.create!(message_params)
  end

  def destroy
    @message.destroy!
  end

  # 更新用のフォームに置き換えることだけに使用する
  def edit
  end

  def update
    @message.update!(message_params)
  end

  private

  # Strong Parameters はサボらずに使っておくこととします
  def message_params
    params.require(:message).permit(:content)
  end

  def set_message
    @message = Message.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AjaxCrudSample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_form.html.erb
<!-- 新規メッセージ投稿用のフォーム -->
<!-- Message.new を 変数 message に変更 -->
<%= form_with model: message do |f| %>
  <%= f.text_field :content %>
  <!-- ボタンの文字を 変数 value に変更 -->
  <%= f.submit value %>
  <% if value == '更新' %>
    <%= link_to '取消', new_message_path, data: { remote: true } %>
  <% end %>
<% end %>

app/views/messages/_message.html.erb
<!-- idを追加 -->
<p id="message-<%= message.id %>">
  <%= message.content %>
  <%= link_to '更新', edit_message_path(message), data: { remote: true } %>
  <!-- 削除のリンクを追加 -->
  <%= link_to '削除', message_path(message),
              method: :delete,
              data: { confirm: '削除しますか?', remote: true } %>
</p>

app/views/messages/create.js.erb
// メッセージ一覧の一番下に新規メッセージを追加する
document.getElementById('messages').insertAdjacentHTML('beforeend', '<%= j(render @message) %>')
// フォームの文字を空にする
document.getElementById('message_content').value = ''

app/views/messages/destroy.js.erb
document.getElementById('message-<%= @message.id %>').outerHTML = ''

app/views/messages/edit.js.erb
// フォームは一つしか無いので， id を使わず，タグ名から要素を取得
// ここの変数宣言に let や const を使用すると２回目にエラーが発生します
var form = document.getElementsByTagName('form')[0]
// フォームを更新用フォームに置き換えます。ボタンの文字は「更新」にします。
form.outerHTML = '<%= j(render 'form', message: @message, value: '更新') %>'

app/views/messages/index.html.erb
<!-- 部分テンプレート _form.html.erb を呼び出す -->
<%= render 'form', message: Message.new, value: '投稿' %>
<hr>
<div id="messages">
  <!-- 各メッセージに対し，部分テンプレート _message.html.erb を呼び出す -->
  <%= render @messages %>
</div>

app/views/messages/new.js.erb
var form = document.getElementsByTagName('form')[0]
form.outerHTML = '<%= j(render 'form', message: Message.new, value: '投稿') %>'

app/views/messages/update.js.erb
// 対応するメッセージを更新
document.getElementById('message-<%= @message.id %>').innerHTML = '<%= j(render @message) %>'
// フォームを新規投稿フォームに戻す
var form = document.getElementsByTagName('form')[0]
form.outerHTML = '<%= j(render 'form', message: Message.new, value: '投稿') %>'